"""add order column

Revision ID: 696a16b17fb9
Revises: 7fc0f114d626
Create Date: 2025-01-24 15:46:53.607344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '696a16b17fb9'
down_revision: Union[str, None] = '7fc0f114d626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('expense', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'order')
    op.drop_column('expense', 'order')
    # ### end Alembic commands ###
